# Generated by Django 3.0.7 on 2023-02-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='des',
            field=models.CharField(default='abc', max_length=300),
            preserve_default=False,
        ),
    ]
